[build]
  base = "."
  command = "npm install -g pnpm --force && pnpm install && pnpm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
